version: "3.9"

services:

  backend:
    container_name: ${HOST_NAME:-'ApiTJMS'}
    hostname: ${HOST_NAME:-'ApiTJMS'}
    network_mode: bridge
    image: alanmartines/api-node-tjms:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 8009
      DOMAIN_SSL: ${DOMAIN_SSL:-}
      SECRET_KEY: ${SECRET_KEY:-09f26e402586e2faa8da4c98a35f1b20d6b033c60}
      CHROME_BIN: ${CHROME_BIN:-}
      WSENDPOINT: ${WSENDPOINT:-}
    volumes:
      - .:/home/ApiTJMS:rw
    ports:
      - ${PORT:-8009}:8009

## Acessar bash do container
# docker exec -it <container id> /bin/sh
# docker exec -it <container id> /bin/bash

## Logs do container
# docker logs -f --tail 1000 ApiTJMS

## Removendo todos os containers e imagens de uma só vez
# docker rm $(docker ps -qa)

## Removendo todas as imagens de uma só vez
# docker rmi $(docker images -aq)

## Removendo imagens
# docker rmi <REPOSITORY>
# docker rmi <IMAGE ID>

## Como obter o endereço IP de um contêiner Docker do host
# https://stack.desenvolvedor.expert/appendix/docker/rede.html
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <IMAGE ID>

# Criar um contêiner
# docker compose -f docker-compose.yml up --build -d